const mainColors = {
  green1: '#0BCAD4',
  green2: '#EDFCFD',
  dark1: '#620000',
  dark2: '#495A75',
  dark3: '#8092AF',
  grey1: '#7D8797',
  grey2: '#E9E9E9',
  grey3: '#EDEEF0',
  grey4: '#B1B7C2',
  grey5: '#989797',
  blue1: '#0066CB',
  black1: '#000000',
  black2: 'rgba(0, 0, 0, 0.5)',
  black3: '#515050',
  red1: '#E06379',
  red2: '#FF6A6A',
  red3: '#FF3434',
  red4: '#CF0000',
};

export const colors = {
  primary: mainColors.red2,
  secondary: mainColors.dark1,
  tertiary: mainColors.red3,
  header: mainColors.red4,
  white: 'white',
  black: 'black',
  disable: mainColors.grey3,
  text: {
    primary: mainColors.dark1,
    secondary: mainColors.grey1,
    menuInactive: mainColors.grey5,
    menuActive: mainColors.red2,
    subTitle: mainColors.dark3,
    startedTitle: mainColors.black3,
  },
  button: {
    primary: {
      background: mainColors.red2,
      text: 'white',
    },
    secondary: {
      background: 'white',
      text: mainColors.dark1,
    },
    disable: {
      background: mainColors.grey3,
      text: mainColors.grey4,
    },
  },
  border: mainColors.grey2,
  cardLight: mainColors.green2,
  loadingBackground: mainColors.black2,
  error: mainColors.red1,
};
